### ISSUE TITLE
Albert Sans not visible on Figma natively (without downloading)

### ISSUE THREAD

**Issue by priyanshsingara** [usted/Albert-Sans#1]
Figma has a built in Google font library integration, still Albert Sans is not visible unless one downloads it on computer via google fonts website. 

Please look into it, and make it available on Figma natively, via built in google font library.

I'm using a windows platform

**Comment by usted** [comment]
Hi @priyanshsingara 
This is unfortunately out of my hands, but it seems like I works now.
