### ISSUE TITLE
Fonts in v1.3 release today are the v1.25 fonts

### ISSUE THREAD

**Issue by kenmcd** [usted/Albert-Sans#2]
The v1.3 release today (2024-03-29) contains the same fonts as in the previous v1.25 release.
Not new fonts.
No `tnum` etc.

**Comment by kenmcd** [comment]
Nope. Not yet.
Now it is just the repo source - no fonts.

**Comment by usted** [comment]
Yes, I had some conflicts on the release build operation, but that should be fixed now. Sorry for the inconvenience. 
Thanks for letting me know.

**Comment by kenmcd** [comment]
Looks good now.
Closing...
